manifest:
  version: "0.10"
  projects:

    # nRF-Connect SDK
    - name: sdk-nrf
      path: nrf
      url: https://github.com/nrfconnect/sdk-nrf.git
      revision: e2a97fe2578a1030f99f85d5e9e61160d261f0e3
      import: true

    # SlimeVR-Tracker-nRF-Receiver
    - name: SlimeVR-Tracker-nRF-Receiver
      url: https://github.com/SlimeVR/SlimeVR-Tracker-nRF-Receiver.git
      path: SlimeVR-Tracker-nRF-Receiver
      revision: main

    # SlimeVR-Tracker-nRF
    - name: SlimeVR-Tracker-nRF
      url: https://github.com/SlimeVR/SlimeVR-Tracker-nRF.git
      path: SlimeVR-Tracker-nRF
      revision: main

      # Stacked-SmolSlime
    - name: Stacked-SmolSlime
      url: https://github.com/LyallUlric/Stacked-SmolSlime.git
      path: Stacked-SmolSlime
      revision: main

    # vqf-c
    - name: vqf-c
      url: https://github.com/sctanf/vqf-c.git
      path: SlimeVR-Tracker-nRF/vqf-c
      revision: master

    # Fusion
    - name: Fusion
      url: https://github.com/xioTechnologies/Fusion.git
      path: SlimeVR-Tracker-nRF/Fusion
      revision: e7d2b41e6506fa9c85492b91becf003262f14977
      
    # NXP-ISSDK-SensorFusion
    - name: NXP-ISSDK-SensorFusion
      url: https://github.com/sctanf/NXP-ISSDK-SensorFusion.git
      path: SlimeVR-Tracker-nRF/NXP-ISSDK-SensorFusion
      revision: main
